### ISSUE TITLE
request for installers

### ISSUE THREAD

**Issue by RomanHGB** [aws/thinkbox-krakatoa-my#1]
Hey!
I was very excited when I heard that Krakatoa was being made open-source. I know that there should be installers via AWS Thinkbox, but I was wondering if they would also be added to this repository? I know it has only been opened very recently, so maybe this is already in the works.

Thanks in advance!
Kind regards, 
Roman

**Comment by RandomInsano** [comment]
The installers for Krakatoa that don’t require licensing are available through the Nimble Studio downloads site at the moment.Details here:AWS Thinkbox products now available free of charge | Amazon Web Servicesaws.amazon.comRegards,EdwinOn Nov 20, 2022, at 7:33 AM, RomanHGB ***@***.***> wrote:﻿
Hey!
I was very excited when I heard that Krakatoa was being made open-source. I know that there should be installers via AWS Thinkbox, but I was wondering if they would also be added to this repository? I know it has only been opened very recently, so maybe this is already in the works.
Thanks in advance!
Kind regards,
Roman
